#229 auto version id retriver getting wrong branch
AoTTG-2/AoTTG-2 pull request #285
Opened 2020-09-18 15:21 UTC by Mi-Sad

All the issue was caused by the fact that the code to get the active branch were prone to failure as it was looking for the git.exe instead of the file which stored the active branch in the repository directly, which is what it does now.
So before it just throw error if the git.exe process were not inside the AoTTG2 repository, now this condition to the installation path of git is no longer required as it check the file directly.
The system itself was already "self-sorting" the multiplayer based on the branch so i only had to make the part of code to get the current 
![Cattura di schermata (1105)](https://user-images.githubusercontent.com/65404701/93615167-55bbad00-f9d3-11ea-8bb2-7e8ec7f709db.png)
branch.

2020-09-19 21:42 UTC, Lithrun requested changes
Two small maintainability comments. Will check on functionality tomorrow afternoon 👍

2020-09-19 21:42 UTC, Lithrun commented on Assets/Scripts/VersionManager.cs
> +            Debug.Log("unable to retrive the branch name");
String should be "Unable to retrieve the branch name" (Typo in retrive)

2020-09-19 21:42 UTC, Lithrun commented on Assets/Scripts/VersionFormatter.cs
> +        Regex regex = new Regex(issueRegex);
Use var over explicitly defining a Type when it is clear what type the right hand side is

2020-09-20 14:57 UTC, Lithrun requested changes
In terms of functionality this is not working as described per #229. I created two builds, one for issue branch 160, and one for this branch. It is expected that only players of branch #229 are able to find lobbies by making use of the "GameVersion" parameter https://doc.photonengine.com/en-us/pun/v1/getting-started/feature-overview#versioning_by_gameversion.

However, with my build of 160 I can join a lobby hosted by 229, and the other way around. This shouldn't be possible as there isn't compatibility between different versions.

2020-09-27 08:03 UTC, Mi-Sad commented
Yeah, need access to the custom server to enable that as game version in not automatically handled for self hosted server as told here from Setup And Connect tutorial from Photon 
![immagine](https://user-images.githubusercontent.com/65404701/94359605-ba000000-00a8-11eb-87f6-0fe1dbe6f3df.png)

2020-09-30 22:03 UTC, Lithrun commented
As discussed, Photon Server needs to be updated for this functionality to work. Once it does, this issue will be closed.

2020-09-30 22:09 UTC, Mi-Sad commented
Wrote a possible solution server side, but the workflow on the server components is still unclear and i can't find clear and detailed documentation. I did not test that solution yet so i have to try if it behave as expected or if everything breaks :'D

2021-02-04 11:41 UTC, Lithrun commented
Picking up this PR, since the PR was associated to #229 which was resolved thanks to a server side fix. The change to read the branch inside the .HEAD file instead of relying on `git.exe` is a cleaner approach.

2021-02-05 19:10 UTC, Lithrun approved these changes

2021-02-05 19:10 UTC, merged