Update ServerSettingsPage.cs
AoTTG-2/AoTTG-2 pull request #292
Opened 2020-09-28 20:47 UTC by sonicv6

2020-09-30 22:02 UTC, Lithrun requested changes
Testing Team notices an issue with this:
```
Both players start on initial level -> MC changes level and restarts -> both players on new level (as it should be) -> non-MC changes level, MC restarts -> MC remains on its level, non-MC goes back to initial level (regardless which level it chooses)
So, in short, as soon as non-MC changes the level locally it seems to be "bound" to the level it joined in on upon each restart. Would be nice if anyone else could confirm this, but I'm pretty sure that's what's happening now.
```
Please investigate and resolve it. Will change to approved once @AoTTG-2/testing-team can confirm it works as intended

2020-09-30 23:02 UTC, sonicv6 commented
I'll investigate some more.

2020-10-06 12:09 UTC, SlowDeepExhalation commented
I checked the latest build, the bug Eisenlocke described seems to have been fixed.  I was unable to find any other issues with level changes not being synchronized between two clients, though I was not _completely_ exhaustive.  No other testers have reported problems either, so here's my go-ahead to merge it.

I don't seem to have been requested to review the PR, so this comment is all I can add.

2020-10-06 15:37 UTC, Lithrun approved these changes

2020-10-06 15:37 UTC, merged