Fixed player titan sliding around on death
AoTTG-2/AoTTG-2 pull request #427
Opened 2020-12-30 02:43 UTC by mash8

2021-01-06 21:50 UTC, Lithrun requested changes

2021-01-06 21:50 UTC, Lithrun commented on Assets/Scripts/Characters/Titan/MindlessTitan.cs
> +            Rigidbody.velocity = new Vector3(0, Rigidbody.velocity.y, 0);
Don't think we need this line of code, as that will instantly kill any existing speed which a titan has. The check to see if the titan is alive in PlayerTitan should be sufficient

2021-01-12 22:25 UTC, mash8 commented on Assets/Scripts/Characters/Titan/MindlessTitan.cs
> +            Rigidbody.velocity = new Vector3(0, Rigidbody.velocity.y, 0);
This is actually necessary for the fix to work. Without it the player titan will still slide around.

2021-02-05 19:43 UTC, Lithrun commented on Assets/Scripts/Characters/Titan/MindlessTitan.cs
> +            Rigidbody.velocity = new Vector3(0, Rigidbody.velocity.y, 0);
See https://github.com/AoTTG-2/AoTTG-2/pull/427/commits/2f5fddc323807e5d37321241ce5e851964f0638a for a solution where PTs will no longer move, and without affecting the previous logic

2021-02-05 19:43 UTC, merged