#429 minimap centering based on camera position
AoTTG-2/AoTTG-2 pull request #513
Opened 2021-01-31 04:15 UTC by DaSquyd

Fixes for #429 #501 #503 #511

2021-02-04 08:02 UTC, WattanaGaming commented
Hey @DaSquyd, mind if I request some stuff? I would like you to bump up the camera height from the player, As of now, it's still having problems with things that are far above the player(for example, the walls). The camera height would at least have to be able to cover the wall's height.

2021-02-04 08:16 UTC, DaSquyd commented
@WattanaGaming The camera already does cover the wall height in this PR. It's at a static Y value of (I think) 250 Unity units. I asked for the highest hill size in #533 because if it's higher than 250, it'll clip like it does in the picture provided there. I can bump that number up pretty easily and quickly, but make sure that mountains can't go above 250 first.

2021-02-04 08:18 UTC, WattanaGaming commented
Let's continue the discussion in Discord 🤔

2021-02-09 20:27 UTC, Lithrun requested changes

2021-02-09 20:27 UTC, Lithrun commented on Assets/MinimapIcon.cs
> +namespace AOT.UI
Namespace should match based on the location of the class. Additionally, don't place them inside the root folder

2021-02-09 20:27 UTC, Lithrun commented on Assets/MinimapIcon.cs
> +        private Rigidbody rb;
Avoid using abbreviations

2021-02-09 20:27 UTC, Lithrun commented on Assets/MinimapIcon.cs
> +            if (transform != null)
Since this is a MonoBehavior, is it even possible for a transform to be null?

2021-02-12 15:19 UTC, Lithrun approved these changes
All good now. Should be able to get merged after the CI is done

2021-02-12 15:56 UTC, merged