#585 dynamic sky toggle
AoTTG-2/AoTTG-2 pull request #608
Opened 2021-03-28 17:09 UTC by FAStre

A new graphics setting "Static Sky Toggle"  has been added to graphics settings that replaces the procedural skybox with a static or HDR one. The toggle significantly improves performance and makes the new lighting system more playable.

The static skybox graphics setting is persisted via playerprefs and the DayAndNightController prefab sets the skybox to an HDR(static) one depending on the CurrentTime variable.

2021-04-18 19:00 UTC, Lithrun requested changes
Don't forget your access modifiers. They help a lot

2021-04-18 19:00 UTC, Lithrun commented on Assets/Scripts/DayNightCycle/ToggleStaticSkybox.cs
> +    public class ToggleStaticSkybox : MonoBehaviour
Don't forget about the access modifiers. These must always be explicitly defined to improve readability

2021-04-18 19:00 UTC, Lithrun commented on Assets/Scripts/DayNightCycle/DayAndNightControl.cs
> +                if (CurrentTime <= 5)
Keep the property at the left side. Switching it between sides can be confusing.

If 5 is less than CurrentTime AND CurrentTime is less than or equal to 8, then...

More readable:
If CurrentTime is Greater than 5 AND Current Time is less than or equal to 8

2021-04-18 19:00 UTC, Lithrun commented on Assets/Scripts/DayNightCycle/DayAndNightControl.cs
> +            if (PlayerPrefs.HasKey("StaticSkybox"))
Magic strings should be in a constant

2021-05-07 13:10 UTC, Lithrun approved these changes

2021-05-07 13:11 UTC, Lithrun commented
Issue is approved, but will wait until #537 is merged.

2021-05-17 16:31 UTC, FAStre commented
> Issue is approved, but will wait until #537 is merged.

537 has been merged here and everything is working as on development branch

2021-05-17 16:36 UTC, Lithrun commented
> 
> 
> > Issue is approved, but will wait until #537 is merged.
> 
> 537 has been merged here and everything is working as on development branch

Alright, will clone the branch, perform some sanity checks, and then see if something explodes.

2021-05-17 19:22 UTC, merged