Fixed Duplication Exploit
AoTTG-2/AoTTG-2 pull request #739
Opened 2021-11-08 08:00 UTC by PeteAniDev

Fixed duplication exploit due to incorrect spectator mode state.

Closes #276

**Contributor guidelines:**
1. A build has been uploaded to the discord #builds channel & has been tested by the testing team
2. Assure the code is inline with the [AoTTG2 coding conventions](https://github.com/AoTTG-2/AoTTG-2/wiki/Code-&-Style-Conventions)
3. Fix any issues that the CI reports (Sonarcloud & unit tests)

After all above conditions are met, @Lithrun will review your Pull Request. Resolve any comments of the reviewer or discuss them if you disagree.

2021-11-09 06:39 UTC, PeteAniDev commented
Since the issue is resolved, I will not continue working on migrating Fenglee Codes to the new system as this "Code Smell" part is related to Gamemode settings. The migration of this should be completed once needChooseSide instance of Fenglee is migrated.

2021-11-09 16:46 UTC, Lithrun commented
> 
> 
> Since the issue is resolved, I will not continue working on migrating Fenglee Codes to the new system as this "Code Smell" part is related to Gamemode settings. The migration of this should be completed once needChooseSide instance of Fenglee is migrated.

That's fine, as Gamemode Settings are significantly changed as per #604 (You can take a peek at #694)

Sonarcloud comments are there as a warning, not as an error. So you can ignore those which aren't relevant to your issue. If there is one which shouldn't be ignored, then you will hear it from me

2021-11-09 17:02 UTC, Lithrun requested changes
See comments. Additionally, what is the exact correlation between the "disabled" state of the SpectatorMode and the actual usage of the EnterSpecMode? Perhaps a cleaner approach would be to call EnterSpecMode whenever the Specmode is enabled / disabled, as then spectator mode specific logic can be within the spectatormode class and the only thing that other classes have to do is to then either enable / disable it

2021-11-09 17:02 UTC, Lithrun commented on Assets/Scripts/FengGameManagerMKII.cs
> +            objArray[0xf5] = null; // Is no longer in the code
If this is no longer required, then delete it

2021-11-09 17:02 UTC, Lithrun commented on Assets/Scripts/UI/Camera/SpectatorMode.cs
> +        private static bool _disable = true;
Rather switch this "disabled" to "enabled", as it's more common to check if something is enabled or not enabled vs disabled or not disabled.

2021-11-09 17:02 UTC, Lithrun commented on Assets/Scripts/UI/Camera/SpectatorMovement.cs
> +    private readonly float baseSpeed = 100f;
A constant (const) would be better here, as this value will not change throughout the usage of the program. With readonly it is technically allowed to modify the value via the constructor, whereas via const you make this more explicitly clear

2021-11-09 17:02 UTC, Lithrun commented on Assets/Scripts/UI/Camera/SpectatorMovement.cs
> +        SpectatorMode.Initialize();
Continuously calling an "Initialize" method doesn't seem right to do every frame. This will keep setting the "_disable" to true.

2021-11-09 17:02 UTC, Lithrun commented on Assets/Scripts/UI/Camera/SpectatorMovement.cs
> +        if (!disable)
You could invert this if statement to make the code a bit more readable. Thus the logic wouldn't be nested within the if statement

Compare:
```
if (disable) return;

// All of the movement logic
```

vs

```
if (!disable)
{
     // All of the movement logic
}
```

2021-11-10 00:18 UTC, PeteAniDev commented on Assets/Scripts/UI/Camera/SpectatorMovement.cs
> +        SpectatorMode.Initialize();
Oh, I forgot that thing. It should be in Awake()

2021-11-10 00:47 UTC, PeteAniDev commented
The EnterSpecMode() can only be used once everything is initialized. For example, when you press 1 to enter the game you switch out of spectator mode. But your body is not initialized yet so the EnterSpecMode() should run after you spawn your hero.
My Unity crashed when trying to put EnterSpecMode() in Toggle(), Disable(), and Enable().

I'll change its name from EnterSpecMode() to UpdateSpecMode() for clarity.

2022-02-13 14:14 UTC, Lithrun approved these changes

2022-02-13 14:21 UTC, merged